export const TIKET_CREATE = 'TIKET_CREATE'
export const TIKET_FETCH = 'TIKET_FETCH'
export const TIKET_UPDATE = 'TIKET_UPDATE'
export const TIKET_DELETE = 'TIKET_DELETE'

export const DASHBOARD_CREATE = 'DASHBOARD_CREATE'
export const DASHBOARD_FETCH = 'DASHBOARD_FETCH'
